config/routes.rb
Rails.application.routes.draw do
  
  resources :movies

  resources :movies, only: [:show] do
    #resources :showings, only: [:show, :index, :destroy]
    resources :showings, only: [:show]
  end

  resources :tickets , only:  [:index, :destroy, :show]

  resources :showings , only: [:show, :index, :destroy] do
    resources :tickets , only:  [:index, :new, :create]
  end

  devise_for :users, :controllers => {registrations: 'registrations', omniauth_callbacks: 'callbacks' }

  devise_scope :user do 
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'application#home'
  

end

app/models/showing.rb
class Showing < ApplicationRecord

  belongs_to :movie
  has_many :tickets
  has_many :users, through: :tickets
  
  before_destroy :check_for_tickets

  validates :show_time, presence: true
  validates :show_date, presence: true
  validate :show_date_cannot_be_in_the_past

  
  def total_tickets
    self.tickets.count
  end

  private

  def show_date_cannot_be_in_the_past
    if show_date.present? && show_date < Date.today
      errors.add(:show_date, "can't be in the past")
    end
  end    

  def check_for_tickets
    if self.tickets.any? 
      errors[:base] << "cannot delete showing that has tickets"
    end
  end
end

app/controllers/showings_controller.rb
class ShowingsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_theater_owner!, except: [:show, :index]

      def show
        @showing = Showing.find_by(id: params[:id])
      end
    
      def destroy
        if @showing = Showing.find_by(id:params[:id])
          if @showing.tickets.any?
            flash[:error] = "Cannot delete showing with tickets"
            redirect_to @showing
          elsif @showing.destroy
            flash[:notice] = "Showing deleted."
            redirect_to @showing.movie
          else 
            flash[:error] =  @showing.errors.full_messages.to_sentence
            redirect_to @showing
          end
        else
          flash[:error] = "Cannot delete showing with tickets"
        end
      end

      
      private
    
      def showing_params
        params.require(:showing).permit(:show_date, :show_time)
      end
    
end

app/helpers/showings_helper.rb
module ShowingsHelper
end

app/views/showings/show.html.erb
<% if @showing && @showing.errors.any? %>
  <div id = "error_explanation">
    <div class = "alert alert-danger">
      The form contains <%= pluralize(@showing.errors.count, "error") %>.
    </div>
    <ul>
      <% @showing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<h1>Showing Details </h1>
<p> <strong> Movie: </strong> <%= @showing.movie.title %> </p>
<p> <strong> Show Date: </strong> <%= @showing.show_date.strftime("%a, %b %e, %Y") %> </p>
<p> <strong> Show time: </strong>  <%= @showing.show_time %> </p>
<br>

<% if current_user.theater_owner %>
    <% if @showing.tickets.any? %>
        <%= link_to "Click to see tickets sold for this showing", showing_tickets_path(@showing) %>
    <% end %>
    <br><br>
    <%= button_to("Delete Showing", { action: "destroy", id: @showing.id }, 
method: :delete, data: { confirm: 'Are you sure you want to delete this showing ?'}) %>
<% else %>
    <%= button_to("Buy Ticket", new_showing_ticket_path(@showing), { method: "get", action:"new"}) %>
<% end %>
<br>