config/routes.rb
Rails.application.routes.draw do
  
  resources :movies

  resources :movies, only: [:show] do
    #resources :showings, only: [:show, :index, :destroy]
    resources :showings, only: [:show]
  end

  resources :tickets , only:  [:index, :destroy, :show]

  resources :showings , only: [:show, :index, :destroy] do
    resources :tickets , only:  [:index, :new, :create]
  end

  devise_for :users, :controllers => {registrations: 'registrations', omniauth_callbacks: 'callbacks' }

  devise_scope :user do 
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'application#home'
  

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :showing

  #scope :unexpired_tickets, -> { joins(:showing).where("showing.show_date >= ?", Date.today )
  scope :my_tickets, -> (me) { where(user: me) }
  
  validates_inclusion_of :ticket_type, :in => %w(Adult Child Senior Student),:message => "{{value}} is not a valid type"
  
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
    before_action :authenticate_user!
    
    @@ticket_price_hash = {"Adult" => 20.00, "Child" => 8.00, "Senior" => 12.00, "Student" => 10.00}
    def index
        if params[:showing_id]
            #theater owner get routed here 
            @showing = Showing.find_by_id(params[:showing_id])
            if !@showing
                flash[:error] =  @showing.errors.full_messages.to_sentence
                #binding.pry
                redirect_to showings_path(@movie)
            end

            if current_user.theater_owner
                @tickets = @showing.tickets
                @tickets_count = @tickets.count
                @showing_revenue = @showing.tickets.sum(:price)
            end
        else
            # regular customer
            @tickets = Ticket.my_tickets(current_user)
            @tickets_count = @tickets.count
        end
    end

    def new
        if params[:showing_id]
            @showing = Showing.find_by_id(params[:showing_id])
            @ticket = @showing.tickets.build
        end
    end

    def create 
        #binding.pry
        @ticket = current_user.tickets.build(ticket_params)
        @ticket.price = @@ticket_price_hash[@ticket.ticket_type]
        if @ticket && @ticket.valid? && @ticket.save 
            
            flash[:notice] = "Ticket purchased"
            redirect_to tickets_path
        else
            flash[:error] = @ticket.errors.full_messages.to_sentence
            render :new
        end
    end

    def show
        if current_user.theater_owner
            @ticket = Ticket.find_by_id(params[:id])
        else
            @ticket = Ticket.my_tickets(current_user).find_by_id(params[:id])
        end
        if !@ticket
            flash[:error] = "Ticket not found"
            if current_user.theater_owner
                redirect_to showing_tickets_path(@showing)
            else
                redirect_to tickets_path  
            end
        end 
    end

    def destroy
        if current_user.theater_owner
            @ticket = Ticket.find_by_id(params[:id])
        else
            @ticket = Ticket.my_tickets(current_user).find_by_id(params[:id])
        end
        if @ticket && @ticket.destroy
            flash[:notice] = "Ticket cancelled"
            
        else
            flash[:error] = "Ticket not cancelled"  
        end
        if current_user.theater_owner
            redirect_to showing_tickets_path(@showing)
        else
            redirect_to tickets_path  
        end
    end

    private
  
    def ticket_params
      params.require(:ticket).permit(:user_id, 
                                  :showing_id, 
                                  :ticket_type,
                                  :price)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/index.html.erb
<% if current_user.theater_owner %>
    <h1> <strong> Movie: </strong><%= @showing.movie.title %> 
    <strong> Show: </strong> <%= @showing.show_date %> <%= @showing.show_time %> </h1>
    <strong>Total revenue for this show: </strong>$ <%= @showing_revenue %> <br>
    <h2> All tickets for this showing:</h2>
 <% else %>
    <h2> All tickets belonging to <%= current_user.name %> </h2>
<% end %>

<% if @tickets_count == 0 %>
    <p> No tickets were found </p>
<% else %>
    <p> <%= @tickets_count %> tickets found: </p>
    <ul>
        <% @tickets.each do |ticket| %>
        <li>
            <% if current_user.theater_owner %>
                <strong> Ticket Number: </strong> <%= ticket.id %> 
                <strong> Type:</strong> <%= ticket.ticket_type %>
                <strong> Customer: </strong><%= ticket.user.name %> 
                    <%=link_to "Ticket Details" ,ticket_path(ticket) %> 
            <% else %>
                <strong><%= ticket.showing.movie.title %></strong> 
                <strong> Show: </strong> <%= ticket.showing.show_date %> <%= ticket.showing.show_time %>  
                    <%=link_to "Ticket Details" ,ticket_path(ticket) %> 
            <% end %>
        </li>
        <% end %>
    </ul>
<% end %>

app/views/tickets/new.html.erb
<%= render 'application/errors' , object: @ticket %>

<h1>Buy a ticket for <%= @showing.show_date %> <%= @showing.show_time %></h1>
<br>
<p>What type of ticket are you purchasing? </p>
<%= form_for [@showing, @ticket] do |f| %>
  <% ticket_type_list = [ 'Adult', 'Child', 'Senior', 'Student'] %>
    <%= f.select :ticket_type, ticket_type_list, selected: 'Adult'  %>
    <%= f.hidden_field :showing_id %>
  <br />
  <%= f.submit %>
<% end %>

app/views/tickets/show.html.erb
<h1>Ticket Details </h1>
<p> <strong> Movie: </strong> <%= link_to @ticket.showing.movie.title , movie_path(@ticket.showing.movie) %> </p>
<p> <strong> Show Date: </strong> <%= @ticket.showing.show_date.strftime('%a, %b %e, %Y') %> </p>
<p> <strong> Show time: </strong>  <%= @ticket.showing.show_time %> </p>
<p> <strong> Ticket type: </strong>  <%= @ticket.ticket_type %> </p>
<p> <strong> Ticket price: </strong>  <%= @ticket.price %> </p>
<br>

<%# Allow theater owners also to cancel tickets in case of issues  %>
    <%= button_to("Cancel Ticket", { action: "destroy", id: @ticket.id }, method: :delete, data: 
    { confirm: 'You are about to cancel this ticket. Are you sure?'}) %>

<br>