config/routes.rb
Rails.application.routes.draw do
  
  resources :movies

  resources :movies, only: [:show] do
    #resources :showings, only: [:show, :index, :destroy]
    resources :showings, only: [:show]
  end

  resources :tickets , only:  [:index, :destroy, :show]

  resources :showings , only: [:show, :index, :destroy] do
    resources :tickets , only:  [:index, :new, :create]
  end

  devise_for :users, :controllers => {registrations: 'registrations', omniauth_callbacks: 'callbacks' }

  devise_scope :user do 
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'application#home'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def home
    end

    private

    def ensure_theater_owner!
        if current_user.theater_owner
            return true 
        else
            return false
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_errors.html.erb
<% if object && object.errors.any? %>
  <div id = "error_explanation">
    <div class = "alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/application/home.html.erb
<h1> Welcome to Your Local Multiplex Theater </h1>
<h2>Dine & Recline</h2>
<p>Experience the best in entertainment & comfort when you lean back, stretch out, 
and settle in for a great time at the movies! We have the coziest, most luxurious seating with seat warmers. 
At our dine-in theatre, you’re invited to put your feet up in one of our special recliners 
complete with personal swiveling tables. 
</p>
<p>
We serve up the very best in fresh ingredients and hand-crafted dishes. With Delivery to Seat, 
you can enjoy restaurant-quality cuisine right in the theatre. Our menus feature hand-crafted appetizers, 
entrées and desserts.
</p>
<p>
<strong>Located at :</strong> 75-57 191st St, Fresh Meadows, NY 11366<br>
<strong>Phone number :</strong> 718-444-4444
</p>
<%# link_to "View Movies", movies_home_path %>