config/routes.rb
Rails.application.routes.draw do
  
  resources :movies

  resources :movies, only: [:show] do
    #resources :showings, only: [:show, :index, :destroy]
    resources :showings, only: [:show]
  end

  resources :tickets , only:  [:index, :destroy, :show]

  resources :showings , only: [:show, :index, :destroy] do
    resources :tickets , only:  [:index, :new, :create]
  end

  devise_for :users, :controllers => {registrations: 'registrations', omniauth_callbacks: 'callbacks' }

  devise_scope :user do 
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'application#home'
  

end

app/views/layouts/_nav.html.erb
<nav>
<ul>
  <li><%= link_to "Home", root_path %> </li>
  <% if !user_signed_in? %>
    <li> <%= link_to "Sign Up", new_user_registration_path %></li>
    <li> <%= link_to "Login", new_user_session_path, method:"post" %> </li>
  <% else %>
    <li> Logged in as: <%= current_user.email %>
    <% if current_user.theater_owner %>
      <li> <%= link_to "Theater Owner View - All movies", movies_path %> </li> 
    <% else %>
      <li> <%= link_to "Customer View - Your Movies", movies_path %> </li> 
      <li> <%= link_to "Your tickets", tickets_path %> </li>
    <% end %>
    <li><%= link_to "Logout", destroy_user_session_path, method:"delete" %> </li>
  <% end %>
</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPortfolioProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav'%>
    <div class="container"
      <% flash.each do |type, msg| %>
        <div class="flash">
          <%= msg %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>